plugins:
  - Movement
  - Elevator
  - Poi
  - Ptz

pad:
  type: ps4
  num_of_buttons: 14
  num_of_axes: 14

Movement:
  type: robotnik_pad_plugins/Movement
  max_linear_speed: 1.5
  max_angular_speed: 3
  cmd_topic_vel: pad_teleop/cmd_vel
  config:
    button_deadman: 5
    axis_linear_x: 1
    axis_linear_y: 0
    axis_angular_z: 2
    button_speed_up: 3
    button_speed_down: 1
    button_kinematic_mode: 7

Elevator:
  type: robotnik_pad_plugins/Elevator
  elevator_service_name: robotnik_base_control/set_elevator
  config:
    deadman: 5
    axis_elevator: 10

# Poi:
#   type: robotnik_pad_plugins/Poi
#   poi_service_name: poi_manager/save_robot_poi
#   config:
#     deadman: 5
#     save_poi_l3: 10
#     save_poi_r3: 11

Ptz:
  type: robotnik_pad_plugins/Ptz
  cmd_topic_ptz: /axis_camera/ptz_command
  
  speed_control: false
  speed_increment: 0.1
  speed_limit: 3.14
  
  position_increment: 0.1
  position_increment_limit: 1.0
  min_pan_position: -3.14
  max_pan_position: 3.14
  min_tilt_position: -1.57
  max_tilt_position: 1.57
  max_zoom_position: 12000

  config:
    deadman: 5
    home: 12
    vertical_arrow:  10
    horizontal_arrow: 9
    zoom_in: 4 
    zoom_out: 6
    step_up: 2 
    step_down: 0
