plugins: 
  - Movement

Movement:
  type: robotnik_pad_plugins/Movement
  config: 
    deadman: 5
    linear_x: 1
    linear_y: 0
    angular_z: 2
    scale_linear: 1.5
    scale_angular: 3
    button_speed_up: 3
    button_speed_down: 1
    button_kinematic_mode: 7

